[profile.default]
evm_version = "cancun"
optimizer_runs = 1000000
solc_version = "0.8.27"
verbosity = 1

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
