[profile.default]
evm_version = "cancun"
optimizer_runs = 1000000
solc_version = "0.8.27"
verbosity = 1
via_ir = true
ffi = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
arbitrum = "${RPC_URL_ARBITRUM}"
base = "${RPC_URL_BASE}"
sepolia = "${RPC_URL_SEPOLIA}"
unichain = "${RPC_URL_UNICHAIN}"
bsc = "${RPC_URL_BSC}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
base = {key = "${BASESCAN_KEY}", url = "https://api.basescan.org/api"}
sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api"}
unichain = {key = "${UNISCAN_KEY}", url = "https://api.uniscan.xyz/api"}
bsc = {key = "${BSCSCAN_KEY}", url = "https://api.bscscan.com/api"}