[profile.default]
evm_version = "cancun"
optimizer_runs = 1000000
solc_version = "0.8.27"
verbosity = 1
via_ir = true
ffi = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
sepolia = "${RPC_URL_SEPOLIA}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api"}
